/**
 * ResultsSection Component
 *
 * Composes ConfidenceIndicator, AlignmentList, GapList, and RecommendationCard
 * to display the complete analysis results with a disclaimer.
 *
 * @see Requirements 3.1, 7.2, 7.6, 10.4, 10.5
 */

import React, { useEffect, useRef } from 'react';
import { MatchAssessment, CONFIDENCE_DISPLAY } from '@/types/fit-analysis';
import { ConfidenceIndicator } from './ConfidenceIndicator';
import { AlignmentList } from './AlignmentList';
import { GapList } from './GapList';
import { RecommendationCard } from './RecommendationCard';
import { LiveRegion } from './LiveRegion';

export interface ResultsSectionProps {
  /** The match assessment to display */
  assessment: MatchAssessment;
  /** Callback when user wants to start a new analysis */
  onNewAnalysis: () => void;
  /** Whether to announce results and manage focus (default: true) */
  announceResults?: boolean;
}

/**
 * ResultsSection displays the complete analysis results
 */
export const ResultsSection: React.FC<ResultsSectionProps> = ({
  assessment,
  onNewAnalysis,
  announceResults = true,
}) => {
  const resultsRef = useRef<HTMLDivElement>(null);

  // Focus management: move focus to results when they appear
  useEffect(() => {
    if (announceResults && resultsRef.current) {
      // Small delay to ensure DOM is ready
      const timer = setTimeout(() => {
        resultsRef.current?.focus();
      }, 100);
      return () => clearTimeout(timer);
    }
  }, [assessment.id, announceResults]);

  // Build announcement message for screen readers
  const confidenceDisplay = CONFIDENCE_DISPLAY[assessment.confidenceScore];
  const announcementMessage = announceResults
    ? `Analysis complete. ${confidenceDisplay.label}: ${confidenceDisplay.description}. ${assessment.alignmentAreas.length} alignment areas and ${assessment.gapAreas.length} gaps identified.`
    : '';

  return (
    <>
      {/* ARIA Live Region for screen reader announcements */}
      <LiveRegion
        message={announcementMessage}
        politeness="polite"
        clearAfter={5000}
      />

      <div
        ref={resultsRef}
        className="space-y-6"
        data-testid="results-section"
        role="region"
        aria-label="Analysis Results"
        tabIndex={-1}
      >
        {/* Header with confidence and new analysis button */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <ConfidenceIndicator
            level={assessment.confidenceScore}
            ariaLabel={`Overall match confidence: ${assessment.confidenceScore.replace('_', ' ')}`}
          />
          <button
            onClick={onNewAnalysis}
            className="px-4 py-2 text-sm font-medium text-blue-600 bg-blue-50 hover:bg-blue-100 rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
            data-testid="new-analysis-button"
          >
            Start New Analysis
          </button>
        </div>

        {/* Recommendation Card - prominent placement */}
        <RecommendationCard recommendation={assessment.recommendation} />

        {/* Alignment and Gap sections */}
        <div className="grid gap-6 lg:grid-cols-2">
          <AlignmentList items={assessment.alignmentAreas} />
          <GapList items={assessment.gapAreas} />
        </div>

        {/* Disclaimer */}
        <div
          className="mt-6 p-4 bg-gray-100 rounded-lg border border-gray-200"
          data-testid="results-disclaimer"
          role="note"
        >
          <p className="text-sm text-gray-600">
            <strong className="text-gray-700">Disclaimer:</strong> This analysis is
            generated by AI based on the portfolio owner&apos;s documented experience.
            It provides an honest assessment but should be used as one input among
            many in your evaluation process. The analysis may not capture all nuances
            of the role or the candidate&apos;s full capabilities.
          </p>
        </div>

        {/* Analysis metadata */}
        <div
          className="text-xs text-gray-400 text-center"
          data-testid="analysis-metadata"
        >
          Analysis performed on{' '}
          {new Date(assessment.timestamp).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          })}
        </div>
      </div>
    </>
  );
};

export default ResultsSection;
