/**
 * ResultsSection Component Tests
 *
 * @see Requirements 3.1, 10.4, 10.5
 */

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { ResultsSection } from './ResultsSection';
import { MatchAssessment } from '@/types/fit-analysis';

describe('ResultsSection', () => {
  const mockAssessment: MatchAssessment = {
    id: 'test-assessment-1',
    timestamp: new Date('2024-01-15T10:30:00Z'),
    jobDescriptionPreview: 'Senior Software Engineer at Tech Company...',
    confidenceScore: 'partial_match',
    alignmentAreas: [
      {
        id: 'align-1',
        title: 'TypeScript Experience',
        description: 'Strong background in TypeScript development',
        evidence: [
          {
            type: 'project',
            title: 'Portfolio Website',
            reference: 'portfolio-site',
            excerpt: 'Built with Next.js and TypeScript',
          },
        ],
      },
    ],
    gapAreas: [
      {
        id: 'gap-1',
        title: 'Machine Learning',
        description: 'No documented ML experience',
        severity: 'moderate',
      },
    ],
    recommendation: {
      type: 'consider',
      summary: 'Worth exploring if ML is not a core requirement',
      details: 'Strong technical foundation but lacks specific ML experience.',
    },
  };

  const mockOnNewAnalysis = jest.fn();

  beforeEach(() => {
    mockOnNewAnalysis.mockClear();
  });

  describe('rendering', () => {
    it('renders results section', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('results-section')).toBeInTheDocument();
    });

    it('renders confidence indicator', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('confidence-indicator')).toBeInTheDocument();
    });

    it('renders recommendation card', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('recommendation-card')).toBeInTheDocument();
    });

    it('renders alignment list', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('alignment-list')).toBeInTheDocument();
    });

    it('renders gap list', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('gap-list')).toBeInTheDocument();
    });

    it('renders disclaimer', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('results-disclaimer')).toBeInTheDocument();
      expect(screen.getByText(/disclaimer/i)).toBeInTheDocument();
      expect(screen.getByText(/generated by ai/i)).toBeInTheDocument();
    });

    it('renders analysis metadata with timestamp', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('analysis-metadata')).toBeInTheDocument();
      expect(screen.getByText(/analysis performed on/i)).toBeInTheDocument();
    });
  });

  describe('new analysis button', () => {
    it('renders new analysis button', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('new-analysis-button')).toBeInTheDocument();
      expect(screen.getByText('Start New Analysis')).toBeInTheDocument();
    });

    it('calls onNewAnalysis when clicked', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      fireEvent.click(screen.getByTestId('new-analysis-button'));
      expect(mockOnNewAnalysis).toHaveBeenCalledTimes(1);
    });
  });

  describe('accessibility', () => {
    it('has proper region role', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByRole('region', { name: /analysis results/i })).toBeInTheDocument();
    });

    it('disclaimer has note role', () => {
      render(
        <ResultsSection
          assessment={mockAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByRole('note')).toBeInTheDocument();
    });
  });

  describe('different confidence levels', () => {
    it('renders strong match assessment', () => {
      const strongAssessment: MatchAssessment = {
        ...mockAssessment,
        confidenceScore: 'strong_match',
        recommendation: {
          type: 'proceed',
          summary: 'Excellent fit for this role',
          details: 'All key requirements are well covered.',
        },
      };

      render(
        <ResultsSection
          assessment={strongAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByText('Strong Match')).toBeInTheDocument();
      expect(screen.getByText('Recommended to Proceed')).toBeInTheDocument();
    });

    it('renders limited match assessment', () => {
      const limitedAssessment: MatchAssessment = {
        ...mockAssessment,
        confidenceScore: 'limited_match',
        recommendation: {
          type: 'reconsider',
          summary: 'May not be the right fit',
          details: 'Significant gaps in key requirements.',
        },
      };

      render(
        <ResultsSection
          assessment={limitedAssessment}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByText('Limited Match')).toBeInTheDocument();
      expect(screen.getByText('May Not Be the Right Fit')).toBeInTheDocument();
    });
  });

  describe('empty lists', () => {
    it('handles empty alignment areas', () => {
      const noAlignments: MatchAssessment = {
        ...mockAssessment,
        alignmentAreas: [],
      };

      render(
        <ResultsSection
          assessment={noAlignments}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('alignment-list-empty')).toBeInTheDocument();
    });

    it('handles empty gap areas', () => {
      const noGaps: MatchAssessment = {
        ...mockAssessment,
        gapAreas: [],
      };

      render(
        <ResultsSection
          assessment={noGaps}
          onNewAnalysis={mockOnNewAnalysis}
        />
      );

      expect(screen.getByTestId('gap-list-empty')).toBeInTheDocument();
    });
  });
});
