import {
  generateResultsMarkdown,
  generateResultsPdf,
  downloadAsFile,
  buildExportFilename,
} from './fit-analysis-export';
import { MatchAssessment } from '@/types/fit-analysis';

const makeAssessment = (overrides: Partial<MatchAssessment> = {}): MatchAssessment => ({
  id: 'test-123',
  timestamp: new Date('2026-03-27T10:30:00Z'),
  jobDescriptionPreview: 'We are looking for a senior engineer...',
  confidenceScore: 'strong_match',
  alignmentAreas: [
    {
      id: 'align-1',
      title: 'Cloud Architecture',
      description: 'Strong background in cloud-native architecture.',
      evidence: [
        {
          type: 'experience',
          title: 'AWS Solutions Architect',
          reference: 'experience/aws',
          excerpt: 'Led the design of multi-region serverless architectures.',
        },
        {
          type: 'project',
          title: 'Portfolio Website',
          reference: 'projects/portfolio',
          excerpt: 'Built with Next.js and TypeScript.',
        },
      ],
    },
  ],
  gapAreas: [
    {
      id: 'gap-1',
      title: 'Machine Learning',
      description: 'No documented ML experience in production systems.',
      severity: 'significant',
    },
    {
      id: 'gap-2',
      title: 'Kubernetes Operations',
      description: 'Limited hands-on Kubernetes experience.',
      severity: 'minor',
    },
  ],
  recommendation: {
    type: 'proceed',
    summary: 'Excellent fit for this role.',
    details: 'Strong technical foundation with extensive cloud architecture experience.',
  },
  ...overrides,
});

describe('generateResultsMarkdown', () => {
  it('includes the job description preview in the header', () => {
    const md = generateResultsMarkdown(makeAssessment(), 'Full JD');
    expect(md).toContain('**Job:** We are looking for a senior engineer...');
  });

  it('includes the portfolio owner name and role', () => {
    const md = generateResultsMarkdown(makeAssessment(), 'Full job description text');
    expect(md).toContain('Daniel Kreuzhofer');
    expect(md).toContain('Senior AI Solutions Architect');
  });

  it('includes the confidence level label', () => {
    const md = generateResultsMarkdown(makeAssessment(), 'JD text');
    expect(md).toContain('Strong Match');
  });

  it('includes the recommendation with type, summary, and details', () => {
    const md = generateResultsMarkdown(makeAssessment(), 'JD text');
    expect(md).toContain('Recommended to Proceed');
    expect(md).toContain('Excellent fit for this role.');
    expect(md).toContain('Strong technical foundation');
  });

  it('lists alignment areas with evidence', () => {
    const md = generateResultsMarkdown(makeAssessment(), 'JD text');
    expect(md).toContain('## Alignment Areas (1)');
    expect(md).toContain('### 1. Cloud Architecture');
    expect(md).toContain('**Experience** — *AWS Solutions Architect*');
    expect(md).toContain('**Project** — *Portfolio Website*');
  });

  it('lists gap areas with severity labels', () => {
    const md = generateResultsMarkdown(makeAssessment(), 'JD text');
    expect(md).toContain('## Gap Areas (2)');
    expect(md).toContain('### 1. Machine Learning (Significant Gap)');
    expect(md).toContain('### 2. Kubernetes Operations (Minor Gap)');
  });

  it('includes the full job description', () => {
    const md = generateResultsMarkdown(makeAssessment(), 'Full JD with all the details');
    expect(md).toContain('Full JD with all the details');
    expect(md).not.toContain('Preview only');
  });

  it('falls back to preview when full JD not available', () => {
    const md = generateResultsMarkdown(makeAssessment());
    expect(md).toContain('We are looking for a senior engineer...');
    expect(md).toContain('Preview only');
  });

  it('includes the disclaimer', () => {
    const md = generateResultsMarkdown(makeAssessment(), 'JD');
    expect(md).toContain('Disclaimer');
    expect(md).toContain('generated by AI');
  });

  it('handles empty alignment areas', () => {
    const md = generateResultsMarkdown(
      makeAssessment({ alignmentAreas: [] }),
      'JD'
    );
    expect(md).toContain('No strong alignment areas were identified');
  });

  it('handles empty gap areas', () => {
    const md = generateResultsMarkdown(makeAssessment({ gapAreas: [] }), 'JD');
    expect(md).toContain('No gaps were identified');
  });

  it('handles partial_match confidence level', () => {
    const md = generateResultsMarkdown(
      makeAssessment({ confidenceScore: 'partial_match' }),
      'JD'
    );
    expect(md).toContain('Partial Match');
  });

  it('handles limited_match confidence level', () => {
    const md = generateResultsMarkdown(
      makeAssessment({ confidenceScore: 'limited_match' }),
      'JD'
    );
    expect(md).toContain('Limited Match');
  });
});

describe('generateResultsPdf', () => {
  it('returns a jsPDF document', () => {
    const doc = generateResultsPdf(makeAssessment(), 'Full JD');
    expect(doc).toBeDefined();
    expect(typeof doc.save).toBe('function');
    expect(typeof doc.output).toBe('function');
  });

  it('produces non-empty output', () => {
    const doc = generateResultsPdf(makeAssessment(), 'Full JD');
    const output = doc.output('arraybuffer');
    expect(output.byteLength).toBeGreaterThan(0);
  });

  it('handles empty alignment and gap areas', () => {
    const doc = generateResultsPdf(
      makeAssessment({ alignmentAreas: [], gapAreas: [] }),
      'JD'
    );
    const output = doc.output('arraybuffer');
    expect(output.byteLength).toBeGreaterThan(0);
  });

  it('handles very long job descriptions without crashing', () => {
    const longJd = 'A'.repeat(5000);
    const doc = generateResultsPdf(makeAssessment(), longJd);
    // Should create multiple pages
    expect(doc.internal.pages.length).toBeGreaterThan(2);
  });
});

describe('buildExportFilename', () => {
  it('includes job title and candidate name in markdown filename', () => {
    const filename = buildExportFilename(makeAssessment());
    expect(filename).toBe(
      'Fit Analysis - We are looking for a senior engineer - Daniel Kreuzhofer.md'
    );
  });

  it('builds pdf filename when specified', () => {
    const filename = buildExportFilename(makeAssessment(), 'pdf');
    expect(filename).toContain('.pdf');
    expect(filename).toContain('Daniel Kreuzhofer');
  });

  it('sanitizes special characters from job title', () => {
    const filename = buildExportFilename(
      makeAssessment({
        jobDescriptionPreview: 'Sr. Engineer (Backend) @ Acme/Corp!',
      })
    );
    expect(filename).toBe(
      'Fit Analysis - Sr Engineer Backend AcmeCorp - Daniel Kreuzhofer.md'
    );
  });

  it('truncates very long job titles', () => {
    const filename = buildExportFilename(
      makeAssessment({
        jobDescriptionPreview: 'A'.repeat(200),
      })
    );
    // Job title portion should be capped at 80 chars
    expect(filename.length).toBeLessThan(200);
  });
});

describe('downloadAsFile', () => {
  it('creates a blob, appends an anchor, clicks it, and cleans up', () => {
    const revokeObjectURL = jest.fn();
    const createObjectURL = jest.fn().mockReturnValue('blob:test-url');
    global.URL.createObjectURL = createObjectURL;
    global.URL.revokeObjectURL = revokeObjectURL;

    const appendChild = jest.spyOn(document.body, 'appendChild').mockImplementation((node) => node);
    const removeChild = jest.spyOn(document.body, 'removeChild').mockImplementation((node) => node);
    const createElement = jest.spyOn(document, 'createElement');

    downloadAsFile('test content', 'test.md', 'text/markdown');

    expect(createObjectURL).toHaveBeenCalled();
    expect(createElement).toHaveBeenCalledWith('a');
    expect(appendChild).toHaveBeenCalled();
    expect(removeChild).toHaveBeenCalled();
    expect(revokeObjectURL).toHaveBeenCalledWith('blob:test-url');

    appendChild.mockRestore();
    removeChild.mockRestore();
    createElement.mockRestore();
  });
});
