/**
 * Fit Analysis Export Utilities
 *
 * Generates downloadable Markdown and PDF reports from fit analysis results.
 * Runs entirely client-side.
 */

import {
  MatchAssessment,
  CONFIDENCE_DISPLAY,
  RECOMMENDATION_DISPLAY,
  GAP_SEVERITY_DISPLAY,
} from '@/types/fit-analysis';
import { PORTFOLIO_OWNER } from '@/lib/portfolio-owner';
import { jsPDF } from 'jspdf';

/**
 * Generate a comprehensive Markdown report from a fit analysis result.
 */
export function generateResultsMarkdown(
  assessment: MatchAssessment,
  jobDescriptionFull?: string
): string {
  const confidence = CONFIDENCE_DISPLAY[assessment.confidenceScore];
  const recommendation = RECOMMENDATION_DISPLAY[assessment.recommendation.type];
  const timestamp = new Date(assessment.timestamp).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const sections: string[] = [];

  // Header
  sections.push(`# Fit Analysis Report

**Job:** ${assessment.jobDescriptionPreview}
**Candidate:** ${PORTFOLIO_OWNER.name} — ${PORTFOLIO_OWNER.role}
**Date:** ${timestamp}`);

  // Overall match
  sections.push(`## Overall Match: ${confidence.label}

${confidence.description}`);

  // Recommendation
  sections.push(`## Recommendation: ${recommendation.label}

**Summary:** ${assessment.recommendation.summary}

${assessment.recommendation.details}`);

  // Alignment areas
  if (assessment.alignmentAreas.length > 0) {
    const alignments = assessment.alignmentAreas
      .map((area, i) => {
        let section = `### ${i + 1}. ${area.title}\n\n${area.description}`;
        if (area.evidence.length > 0) {
          const evidenceLines = area.evidence
            .map((e) => `- **${capitalize(e.type)}** — *${e.title}*: "${e.excerpt}"`)
            .join('\n');
          section += `\n\n**Supporting Evidence:**\n${evidenceLines}`;
        }
        return section;
      })
      .join('\n\n');

    sections.push(`## Alignment Areas (${assessment.alignmentAreas.length})\n\n${alignments}`);
  } else {
    sections.push('## Alignment Areas\n\nNo strong alignment areas were identified.');
  }

  // Gap areas
  if (assessment.gapAreas.length > 0) {
    const gaps = assessment.gapAreas
      .map((gap, i) => {
        const severity = GAP_SEVERITY_DISPLAY[gap.severity];
        return `### ${i + 1}. ${gap.title} (${severity.label})\n\n${gap.description}`;
      })
      .join('\n\n');

    sections.push(`## Gap Areas (${assessment.gapAreas.length})\n\n${gaps}`);
  } else {
    sections.push('## Gap Areas\n\nNo gaps were identified.');
  }

  // Job description
  const jdText = jobDescriptionFull || assessment.jobDescriptionPreview;
  const jdNote =
    !jobDescriptionFull && assessment.jobDescriptionPreview
      ? '\n\n*(Preview only — full job description not available)*'
      : '';
  sections.push(`## Job Description Analyzed\n\n${jdText}${jdNote}`);

  // Disclaimer
  sections.push(
    `---\n\n*Disclaimer: This analysis is generated by AI based on the portfolio owner's documented experience. It provides an honest assessment but should be used as one input among many in your evaluation process. The analysis may not capture all nuances of the role or the candidate's full capabilities.*`
  );

  return sections.join('\n\n---\n\n');
}

// =============================================================================
// PDF Generation
// =============================================================================

const PDF_MARGIN = 20;
const PDF_WIDTH = 210; // A4 width in mm
const PDF_CONTENT_WIDTH = PDF_WIDTH - 2 * PDF_MARGIN;
const PDF_LINE_HEIGHT = 5;

interface PdfCursor {
  y: number;
  doc: jsPDF;
}

function ensureSpace(cursor: PdfCursor, needed: number): void {
  if (cursor.y + needed > 280) {
    cursor.doc.addPage();
    cursor.y = PDF_MARGIN;
  }
}

function addTitle(cursor: PdfCursor, text: string): void {
  ensureSpace(cursor, 12);
  cursor.doc.setFont('helvetica', 'bold');
  cursor.doc.setFontSize(16);
  cursor.y += 4;
  cursor.doc.text(text, PDF_MARGIN, cursor.y);
  cursor.y += 8;
}

function addHeading(cursor: PdfCursor, text: string): void {
  ensureSpace(cursor, 14);
  cursor.y += 4;
  cursor.doc.setDrawColor(200, 200, 200);
  cursor.doc.line(PDF_MARGIN, cursor.y, PDF_WIDTH - PDF_MARGIN, cursor.y);
  cursor.y += 6;
  cursor.doc.setFont('helvetica', 'bold');
  cursor.doc.setFontSize(12);
  cursor.doc.text(text, PDF_MARGIN, cursor.y);
  cursor.y += 7;
}

function addSubheading(cursor: PdfCursor, text: string): void {
  ensureSpace(cursor, 10);
  cursor.y += 2;
  cursor.doc.setFont('helvetica', 'bold');
  cursor.doc.setFontSize(10);
  cursor.doc.text(text, PDF_MARGIN, cursor.y);
  cursor.y += 6;
}

function addText(cursor: PdfCursor, text: string, indent = 0): void {
  cursor.doc.setFont('helvetica', 'normal');
  cursor.doc.setFontSize(10);
  const lines = cursor.doc.splitTextToSize(text, PDF_CONTENT_WIDTH - indent);
  for (const line of lines) {
    ensureSpace(cursor, PDF_LINE_HEIGHT);
    cursor.doc.text(line, PDF_MARGIN + indent, cursor.y);
    cursor.y += PDF_LINE_HEIGHT;
  }
}

function addBoldText(cursor: PdfCursor, text: string, indent = 0): void {
  cursor.doc.setFont('helvetica', 'bold');
  cursor.doc.setFontSize(10);
  const lines = cursor.doc.splitTextToSize(text, PDF_CONTENT_WIDTH - indent);
  for (const line of lines) {
    ensureSpace(cursor, PDF_LINE_HEIGHT);
    cursor.doc.text(line, PDF_MARGIN + indent, cursor.y);
    cursor.y += PDF_LINE_HEIGHT;
  }
}

function addSmallText(cursor: PdfCursor, text: string): void {
  cursor.doc.setFont('helvetica', 'italic');
  cursor.doc.setFontSize(8);
  const lines = cursor.doc.splitTextToSize(text, PDF_CONTENT_WIDTH);
  for (const line of lines) {
    ensureSpace(cursor, 4);
    cursor.doc.text(line, PDF_MARGIN, cursor.y);
    cursor.y += 4;
  }
}

/**
 * Generate a PDF report from a fit analysis result.
 * Returns the jsPDF document for testing or direct download.
 */
export function generateResultsPdf(
  assessment: MatchAssessment,
  jobDescriptionFull?: string
): jsPDF {
  const doc = new jsPDF();
  const confidence = CONFIDENCE_DISPLAY[assessment.confidenceScore];
  const recommendation = RECOMMENDATION_DISPLAY[assessment.recommendation.type];
  const timestamp = new Date(assessment.timestamp).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const cursor: PdfCursor = { y: PDF_MARGIN, doc };

  // Title
  addTitle(cursor, 'Fit Analysis Report');

  // Metadata
  addBoldText(cursor, `Job: ${assessment.jobDescriptionPreview}`);
  addText(cursor, `Candidate: ${PORTFOLIO_OWNER.name} — ${PORTFOLIO_OWNER.role}`);
  addText(cursor, `Date: ${timestamp}`);
  cursor.y += 2;

  // Overall match
  addHeading(cursor, `Overall Match: ${confidence.label}`);
  addText(cursor, confidence.description);

  // Recommendation
  addHeading(cursor, `Recommendation: ${recommendation.label}`);
  addBoldText(cursor, `Summary: ${assessment.recommendation.summary}`);
  cursor.y += 2;
  addText(cursor, assessment.recommendation.details);

  // Alignment areas
  if (assessment.alignmentAreas.length > 0) {
    addHeading(cursor, `Alignment Areas (${assessment.alignmentAreas.length})`);
    assessment.alignmentAreas.forEach((area, i) => {
      addSubheading(cursor, `${i + 1}. ${area.title}`);
      addText(cursor, area.description, 4);
      if (area.evidence.length > 0) {
        cursor.y += 2;
        addBoldText(cursor, 'Supporting Evidence:', 4);
        area.evidence.forEach((e) => {
          addText(cursor, `• ${capitalize(e.type)} — ${e.title}: "${e.excerpt}"`, 8);
        });
      }
      cursor.y += 2;
    });
  } else {
    addHeading(cursor, 'Alignment Areas');
    addText(cursor, 'No strong alignment areas were identified.');
  }

  // Gap areas
  if (assessment.gapAreas.length > 0) {
    addHeading(cursor, `Gap Areas (${assessment.gapAreas.length})`);
    assessment.gapAreas.forEach((gap, i) => {
      const severity = GAP_SEVERITY_DISPLAY[gap.severity];
      addSubheading(cursor, `${i + 1}. ${gap.title} (${severity.label})`);
      addText(cursor, gap.description, 4);
      cursor.y += 2;
    });
  } else {
    addHeading(cursor, 'Gap Areas');
    addText(cursor, 'No gaps were identified.');
  }

  // Job description
  addHeading(cursor, 'Job Description Analyzed');
  const jdText = jobDescriptionFull || assessment.jobDescriptionPreview;
  addText(cursor, jdText);
  if (!jobDescriptionFull && assessment.jobDescriptionPreview) {
    cursor.y += 2;
    addSmallText(cursor, '(Preview only — full job description not available)');
  }

  // Disclaimer
  cursor.y += 6;
  doc.setDrawColor(200, 200, 200);
  doc.line(PDF_MARGIN, cursor.y, PDF_WIDTH - PDF_MARGIN, cursor.y);
  cursor.y += 4;
  addSmallText(
    cursor,
    "Disclaimer: This analysis is generated by AI based on the portfolio owner's documented experience. It provides an honest assessment but should be used as one input among many in your evaluation process. The analysis may not capture all nuances of the role or the candidate's full capabilities."
  );

  return doc;
}

// =============================================================================
// Download helpers
// =============================================================================

/**
 * Trigger a file download in the browser.
 */
export function downloadAsFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Build a filename for the download (without extension).
 */
export function buildExportFilename(assessment: MatchAssessment, ext: string = 'md'): string {
  const date = new Date(assessment.timestamp).toISOString().split('T')[0];
  const confidence = assessment.confidenceScore.replace(/_/g, '-');
  return `fit-analysis-${date}-${confidence}.${ext}`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
